#!/usr/bin/env python3
"""Regenerates docs/opportunities.js from the state files so docs/feed.html
can load data over file:// without a server. Run after every cycle."""
import json, pathlib, datetime

root = pathlib.Path(__file__).resolve().parents[1]
opps = json.loads((root / "state" / "opportunities.json").read_text())
board = json.loads((root / "state" / "deadline-board.json").read_text())

out = (
    "// Auto generated by scripts/build_dashboard.py. Do not edit by hand.\n"
    f"window.FEED_UPDATED = {json.dumps(datetime.datetime.now().strftime('%B %d, %Y %H:%M'))};\n"
    f"window.FEED_DATA = {json.dumps(opps.get('items', []), indent=1)};\n"
    f"window.DEADLINE_BOARD = {json.dumps(board.get('windows', []), indent=1)};\n"
)
(root / "docs" / "opportunities.js").write_text(out)
print(f"Wrote docs/opportunities.js with {len(opps.get('items', []))} items "
      f"and {len(board.get('windows', []))} deadline windows.")
